### ISSUE TITLE
Change background color of cards

### ISSUE THREAD

**Issue by JaynouOliver** [Tech-Squad-Community/techsquad-community-website#1] opened 2022-02-21 19:55 UTC
![image](https://user-images.githubusercontent.com/88646338/155017969-e7d5b5e5-21a6-4f0e-b977-f85d7df85411.png)

Change the background color according to the color of the tags.

**Comment by ehtishama** [comment] 2022-02-22 03:54
@JaynouOliver What would be the colour of the tag then? e.g. If the background of the card with the development tag has yellow then what should be the colour of the tag itself? yellow?

Also, I want to work on this issue. Can you please assign it to me? 

Thanks.

**Comment by ronitblenz** [comment] 2022-02-22 08:27
You can color the tag as white or a lighter shade of yellow, I think its making sense.
And the issues will be assigned 1st march onwards according to gssoc guideline.

**Comment by ronitblenz** [comment] 2022-02-25 08:43
You can start working on the issue from now on, I will assign you on 1st march, then you can create a PR 
Because you have much time left

**Comment by ronitblenz** [comment] 2022-02-28 18:48
you are assigned, start working on the issue and create a PR... Good luck

**Comment by sohan2503001** [comment] 2022-03-01 02:27
i would like to work on these issue

**Comment by mahi-19** [comment] 2022-03-01 16:46
I am a GSSOC'22 participant and want to work on this issue, assign this issue to me

**Comment by ronitblenz** [comment] 2022-03-01 18:50
@ehtishama Any updates? If not, I would forward the issue to someone next to you in the queue

**Comment by ronitblenz** [comment] 2022-03-02 05:34
You can simply run on it local host. No need to run YARN or NPM🥲

**Comment by ronitblenz** [comment] 2022-03-02 05:34
And make sure you make a branch, it seems to be the dev branch....😀

**Comment by ronitblenz** [comment] 2022-03-02 15:32
@ehtishama You are allotted 24 hrs for the easy issue... You are given much more than that. If the issue is not solved within today, it will be assigned to the person waiting next to you

**Comment by HarshKumarChoudary** [comment] 2022-03-03 03:03
If the issue is still available, please consider me for that. Thanks

**Comment by ronitblenz** [comment] 2022-03-03 03:12
@sohan2503001 commented before you. So, it's a first come first serve basis. You can check out other issues or create one after asking me or other mentors.

**Comment by ronitblenz** [comment] 2022-03-03 03:13
@sohan2503001 You are assigned, you can work on the issue. It's a level1 issue. you have 24 hours to contribute

**Comment by sohan2503001** [comment] 2022-03-03 03:29
@ronitblenz I have solved the issue , can i create the PR

**Comment by ronitblenz** [comment] 2022-03-03 03:37
Yes sure

**Comment by ronitblenz** [comment] 2022-03-03 03:37
Yes sure

**Comment by ronitblenz** [comment] 2022-03-03 08:06
Make the pr @sohan2503001

**Closed** 2022-03-03 09:43 UTC
Labels: good first issue, GSSoC22, assigned, code, Level1
